<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" retried="3" total="7" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="RetryFailedSuit" duration-ms="94636" started-at="2020-05-25T16:38:41 IST" finished-at="2020-05-25T16:40:16 IST">
    <groups>
    </groups>
    <test name="RetryMultipleFailedTestCases" duration-ms="94636" started-at="2020-05-25T16:38:41 IST" finished-at="2020-05-25T16:40:16 IST">
      <class name="com.primeclass.qa.testcases.LoginPageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="setup" is-config="true" duration-ms="16983" started-at="2020-05-25T16:38:41 IST" finished-at="2020-05-25T16:38:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="verifyLoginPageTitleTest()[pri:1, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="verifyLoginPageTitleTest" duration-ms="337" started-at="2020-05-25T16:38:58 IST" finished-at="2020-05-25T16:38:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="tearDown" is-config="true" duration-ms="1056" started-at="2020-05-25T16:38:58 IST" finished-at="2020-05-25T16:38:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="setup" is-config="true" duration-ms="10996" started-at="2020-05-25T16:38:59 IST" finished-at="2020-05-25T16:39:10 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="VerfiyCenterLinkButton()[pri:2, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="VerfiyCenterLinkButton" duration-ms="160" started-at="2020-05-25T16:39:10 IST" finished-at="2020-05-25T16:39:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerfiyCenterLinkButton -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="tearDown" is-config="true" duration-ms="1507" started-at="2020-05-25T16:39:11 IST" finished-at="2020-05-25T16:39:12 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="setup" is-config="true" duration-ms="10140" started-at="2020-05-25T16:39:12 IST" finished-at="2020-05-25T16:39:22 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="verifyHomePageHeaderTest()[pri:3, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="verifyHomePageHeaderTest" duration-ms="195" retried="true" started-at="2020-05-25T16:39:22 IST" finished-at="2020-05-25T16:39:22 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Header value is not matched expected [Aakash Distance Learning11] but found [Aakash Distance Learning]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Header value is not matched expected [Aakash Distance Learning11] but found [Aakash Distance Learning]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.primeclass.qa.testcases.LoginPageTest.verifyHomePageHeaderTest(LoginPageTest.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageHeaderTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="tearDown" is-config="true" duration-ms="993" started-at="2020-05-25T16:39:22 IST" finished-at="2020-05-25T16:39:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="setup" is-config="true" duration-ms="11371" started-at="2020-05-25T16:39:23 IST" finished-at="2020-05-25T16:39:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="verifyHomePageHeaderTest()[pri:3, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="verifyHomePageHeaderTest" duration-ms="64" retried="true" started-at="2020-05-25T16:39:35 IST" finished-at="2020-05-25T16:39:35 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Header value is not matched expected [Aakash Distance Learning11] but found [Aakash Distance Learning]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Header value is not matched expected [Aakash Distance Learning11] but found [Aakash Distance Learning]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.primeclass.qa.testcases.LoginPageTest.verifyHomePageHeaderTest(LoginPageTest.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageHeaderTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="tearDown" is-config="true" duration-ms="967" started-at="2020-05-25T16:39:35 IST" finished-at="2020-05-25T16:39:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="setup" is-config="true" duration-ms="10196" started-at="2020-05-25T16:39:36 IST" finished-at="2020-05-25T16:39:46 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="verifyHomePageHeaderTest()[pri:3, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="verifyHomePageHeaderTest" duration-ms="56" retried="true" started-at="2020-05-25T16:39:46 IST" finished-at="2020-05-25T16:39:46 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Header value is not matched expected [Aakash Distance Learning11] but found [Aakash Distance Learning]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Header value is not matched expected [Aakash Distance Learning11] but found [Aakash Distance Learning]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.primeclass.qa.testcases.LoginPageTest.verifyHomePageHeaderTest(LoginPageTest.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageHeaderTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="tearDown" is-config="true" duration-ms="1279" started-at="2020-05-25T16:39:46 IST" finished-at="2020-05-25T16:39:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="setup" is-config="true" duration-ms="12377" started-at="2020-05-25T16:39:47 IST" finished-at="2020-05-25T16:40:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyHomePageHeaderTest()[pri:3, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="verifyHomePageHeaderTest" duration-ms="135" started-at="2020-05-25T16:40:00 IST" finished-at="2020-05-25T16:40:00 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Header value is not matched expected [Aakash Distance Learning11] but found [Aakash Distance Learning]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Header value is not matched expected [Aakash Distance Learning11] but found [Aakash Distance Learning]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.primeclass.qa.testcases.LoginPageTest.verifyHomePageHeaderTest(LoginPageTest.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageHeaderTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="tearDown" is-config="true" duration-ms="2636" started-at="2020-05-25T16:40:00 IST" finished-at="2020-05-25T16:40:03 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="setup" is-config="true" duration-ms="11050" started-at="2020-05-25T16:40:03 IST" finished-at="2020-05-25T16:40:14 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="contactUsTest()[pri:4, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="contactUsTest" duration-ms="1124" started-at="2020-05-25T16:40:14 IST" finished-at="2020-05-25T16:40:15 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.primeclass.qa.testcases.LoginPageTest@4b553d26]" name="tearDown" is-config="true" duration-ms="899" started-at="2020-05-25T16:40:15 IST" finished-at="2020-05-25T16:40:16 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.primeclass.qa.testcases.LoginPageTest -->
    </test> <!-- RetryMultipleFailedTestCases -->
  </suite> <!-- RetryFailedSuit -->
</testng-results>
