<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CORPLPTP000053" name="com.primeclass.qa.testcases.StudentSignupPageTest" tests="1" failures="0" timestamp="2020-05-23T15:27:19 IST" time="1.617" errors="1">
  <testcase name="stu_Signup_Page" time="1.617" classname="com.primeclass.qa.testcases.StudentSignupPageTest">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
[public void com.primeclass.qa.testcases.StudentSignupPageTest.stu_Signup_Page(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: stu_Signup_Page([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) Arun Pandey,(java.lang.String) 11800000222,(java.lang.String) 0000,(java.lang.String) arunpandey17@yopmail.com,(java.lang.String) arun1234,(java.lang.String) arun1234,(java.lang.String) 12,(java.lang.String) Delhi,(java.lang.String) Delhi - Pitampura (Engineering),(java.lang.String) Arun,(java.lang.String) Pandey,(java.lang.String) Ak Pandey,(java.lang.String) 9560370108,(java.lang.String) arunpandey.pus@aesl.in,(java.lang.String) JKHouse- Plot 32 Pusa road,(java.lang.String) Noida,(java.lang.String) 201305,(java.lang.String) Uttar Pradesh]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.primeclass.qa.testcases.StudentSignupPageTest.stu_Signup_Page(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: stu_Signup_Page([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) Arun Pandey,(java.lang.String) 11800000222,(java.lang.String) 0000,(java.lang.String) arunpandey17@yopmail.com,(java.lang.String) arun1234,(java.lang.String) arun1234,(java.lang.String) 12,(java.lang.String) Delhi,(java.lang.String) Delhi - Pitampura (Engineering),(java.lang.String) Arun,(java.lang.String) Pandey,(java.lang.String) Ak Pandey,(java.lang.String) 9560370108,(java.lang.String) arunpandey.pus@aesl.in,(java.lang.String) JKHouse- Plot 32 Pusa road,(java.lang.String) Noida,(java.lang.String) 201305,(java.lang.String) Uttar Pradesh]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- stu_Signup_Page -->
  <system-out/>
</testsuite> <!-- com.primeclass.qa.testcases.StudentSignupPageTest -->
